name: Definition of Done
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-dod:
    runs-on: ubuntu-latest
    steps:
      - name: Check DoD
        uses: actions/checkout@v2
      - name: Check PR against DoD
        run: |
          # Get the PR description
          pr_description=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            | jq -r .body)

          # Read the DoD file and store checkpoints in an array
          dod_file="dod.yaml"
          mapfile -t dod_checkpoints < <(yq eval '.dod[]' "$dod_file")

          # Check if all DoD checkpoints are in the PR description
          missing_checkpoints=()
          for checkpoint in "${dod_checkpoints[@]}"; do
            if ! echo "$pr_description" | grep -qF "$checkpoint"; then
              missing_checkpoints+=("$checkpoint")
            fi
          done

          # If any DoD checkpoints are missing, add them to the PR description
          if [ ${#missing_checkpoints[@]} -gt 0 ]; then
            new_description="$pr_description"
            for checkpoint in "${missing_checkpoints[@]}"; do
              new_description="${new_description}"$'\n'"$checkpoint"
            done
            echo "Adding missing DoD checkpoints to PR description..."
            curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -X PATCH \
              -d "{\"body\":\"$new_description\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
