name: Definition of Done
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-dod:
    runs-on: ubuntu-latest
    steps:
      - name: Check DoD
        uses: actions/checkout@v2
      - name: Definition of Done (DoD) checker
        uses: platisd/definition-of-done@v2.0.0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_DOD_YAML: dod.yaml
