name: Definition of Done
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-dod:
    runs-on: ubuntu-latest
    steps:
      - name: Check DoD
        uses: actions/checkout@v2
      - name: Check PR against DoD
        run: |
          # Read the DoD file and store checkpoints in an array
          dod_file="dod.yaml"
          mapfile -t dod_checkpoints < <(yq eval '.dod[]' "$dod_file")

          # Get the PR description
          pr_description=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            | jq -r .body)

          # Check if all DoD checkpoints are in the PR description
          for checkpoint in "${dod_checkpoints[@]}"; do
            if ! echo "$pr_description" | grep -q "$checkpoint"; then
              echo "Missing DoD checkpoint: $checkpoint"
              exit 1
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
